[program:salono-scheduler]
process_name=%(program_name)s
command=php artisan schedule:work
directory=/var/www/salono
autostart=true
autorestart=true
user=www-data
redirect_stderr=true
stdout_logfile=/var/www/salono/storage/logs/scheduler.log
